#include <stdio.h>

#include <fft.h>

#include <util.h>

#define TEST_WRAPPER(_fft, _f, _positions, _res)                               \
    do {                                                                       \
        if (test((_fft), (_f), (_positions), (_res))) {                        \
            free_all((_fft));                                                  \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static int test(const FFT_t *fft, symbol_seq_t f, const uint16_t *positions,
                symbol_seq_t res) {
    symbol_seq_t _res;
    int ret;

    ret = seq_alloc(res.symbol_size, res.length, &_res);
    if (ret) {
        printf("ERROR: seq_alloc returned %d\n", ret);
        return ret;
    }

    fft_transform(fft, f, positions, _res);

    if (!util_seq_eq(_res, res)) {
        printf("ERROR: fft_transform(...): incorrect res:\n");

        printf("\tcorrect = ");
        util_seq_printf(res);
        printf("\n");

        printf("\tactual  = ");
        util_seq_printf(_res);
        printf("\n");

        ret = 1;
    }

    seq_free(&_res);

    return ret;
}

static int free_all(FFT_t *fft) {
    GF_t *gf = fft->gf;

    fft_free(fft);
    gf_free(gf);
}

int main(void) {
    GF_t _gf;
    FFT_t _fft;
    FFT_t *fft = &_fft;

    {
        GF_t *gf = &_gf;
        int ret;

        ret = gf_alloc(gf);
        if (ret) {
            printf("ERROR: gf_alloc returned %d\n", ret);
            return ret;
        }

        gf_init(gf);

        ret = fft_alloc(fft);
        if (ret) {
            printf("ERROR: fft_alloc returned %d\n", ret);
            gf_free(gf);
            return ret;
        }

        fft_init(fft, gf);
    }

    // Test data obtained by SageMath.
    // Code also was generated by Python and SageMath.

    // Test 1
    {
        element_t f_symbols_data[18][1] = {
            {59446}, {52683}, {24240}, {17739}, {22147}, {6845},
            {16105}, {43613}, {43951}, {51446}, {58809}, {26190},
            {34396}, {23440}, {3014},  {10094}, {35896}, {16871}};
        element_t res_symbols_data[11][1] = {{15001}, {28408}, {13550}, {14466},
                                             {56755}, {60517}, {774},   {45685},
                                             {40231}, {37183}, {38313}};
        symbol_t f_symbols[18] = {
            {.data = f_symbols_data[0]},  {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]},  {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]},  {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]},  {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]},  {.data = f_symbols_data[9]},
            {.data = f_symbols_data[10]}, {.data = f_symbols_data[11]},
            {.data = f_symbols_data[12]}, {.data = f_symbols_data[13]},
            {.data = f_symbols_data[14]}, {.data = f_symbols_data[15]},
            {.data = f_symbols_data[16]}, {.data = f_symbols_data[17]}};
        symbol_t res_symbols[11] = {
            {.data = res_symbols_data[0]}, {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]}, {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]}, {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]}, {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]}, {.data = res_symbols_data[9]},
            {.data = res_symbols_data[10]}};
        symbol_seq_t f = {.symbol_size = 1, .length = 18, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 1, .length = 11, .symbols = res_symbols};
        uint16_t positions[18] = {35895, 7996,  51848, 25836, 56495, 24526,
                                  3582,  25141, 22472, 33095, 45520, 53527,
                                  31338, 26227, 1880,  6059,  41713, 56219};

        TEST_WRAPPER(fft, f, positions, res);
    }

    // Test 2
    {
        element_t f_symbols_data[8][2] = {
            {28848, 29441}, {41827, 16357}, {48099, 25582}, {36814, 19665},
            {26286, 27808}, {21995, 64922}, {29935, 15976}, {39777, 34133}};
        element_t res_symbols_data[8][2] = {
            {15157, 18908}, {53272, 32519}, {47546, 14143}, {15429, 55548},
            {5855, 32019},  {1107, 41938},  {2189, 27451},  {56815, 41213}};
        symbol_t f_symbols[8] = {
            {.data = f_symbols_data[0]}, {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]}, {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]}, {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]}, {.data = f_symbols_data[7]}};
        symbol_t res_symbols[8] = {
            {.data = res_symbols_data[0]}, {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]}, {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]}, {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]}, {.data = res_symbols_data[7]}};
        symbol_seq_t f = {.symbol_size = 2, .length = 8, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 2, .length = 8, .symbols = res_symbols};
        uint16_t positions[8] = {56605, 28232, 15207, 33617,
                                 44423, 26975, 22610, 19572};

        TEST_WRAPPER(fft, f, positions, res);
    }

    // Test 3
    {
        element_t f_symbols_data[10][3] = {
            {7390, 16992, 41253},  {55840, 5814, 62251},  {44507, 25711, 58349},
            {7717, 7568, 35910},   {13016, 23186, 63451}, {26949, 880, 58533},
            {37688, 63842, 59228}, {29513, 36129, 39709}, {32650, 26669, 26130},
            {63060, 43722, 6065}};
        element_t res_symbols_data[10][3] = {
            {18226, 49775, 9017}, {47713, 41824, 23832}, {54454, 65085, 13045},
            {5290, 10467, 13189}, {32767, 34007, 9781},  {60042, 59039, 32428},
            {23244, 4359, 47772}, {8867, 42123, 41805},  {49305, 13080, 1584},
            {4349, 51548, 45905}};
        symbol_t f_symbols[10] = {
            {.data = f_symbols_data[0]}, {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]}, {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]}, {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]}, {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]}, {.data = f_symbols_data[9]}};
        symbol_t res_symbols[10] = {
            {.data = res_symbols_data[0]}, {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]}, {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]}, {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]}, {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]}, {.data = res_symbols_data[9]}};
        symbol_seq_t f = {.symbol_size = 3, .length = 10, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 3, .length = 10, .symbols = res_symbols};
        uint16_t positions[10] = {26757, 33761, 16356, 44934, 12891,
                                  1536,  58733, 745,   49191, 55606};

        TEST_WRAPPER(fft, f, positions, res);
    }

    free_all(fft);

    return 0;
}