#include <stdio.h>

#include <fft.h>

#include <util.h>

#define TEST_WRAPPER(_fft, _f, _res, _components)                              \
    do {                                                                       \
        if (test((_fft), (_f), (_res), (_components))) {                       \
            free_all((_fft));                                                  \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static int test(const FFT_t* fft, symbol_seq_t f, symbol_seq_t res,
                const uint16_t* components) {
    symbol_seq_t _res;
    int ret;

    ret = seq_alloc(res.symbol_size, res.length, &_res);
    if (ret) {
        printf("ERROR: seq_alloc returned %d\n", ret);
        return ret;
    }

    fft_partial_transform(fft, f, _res, components);

    if (!util_seq_eq(_res, res)) {
        printf("ERROR: fft_partial_transform(...): incorrect res:\n");

        printf("\tcorrect = ");
        util_seq_printf(res);
        printf("\n");

        printf("\tactual  = ");
        util_seq_printf(_res);
        printf("\n");

        ret = 1;
    }

    seq_free(&_res);

    return ret;
}

static int free_all(FFT_t* fft) {
    GF_t* gf = fft->gf;

    fft_free(fft);
    gf_free(gf);
}

int main(void) {
    GF_t _gf;
    FFT_t _fft;
    FFT_t* fft = &_fft;

    {
        GF_t* gf = &_gf;
        int ret;

        ret = gf_alloc(gf);
        if (ret) {
            printf("ERROR: gf_alloc returned %d\n", ret);
            return ret;
        }

        gf_init(gf);

        ret = fft_alloc(fft);
        if (ret) {
            printf("ERROR: fft_alloc returned %d\n", ret);
            gf_free(gf);
            return ret;
        }

        fft_init(fft, gf);
    }

    // Test data obtained by SageMath.
    // Code also was generated by Python and SageMath.

    // Test 1
    {
        element_t f_symbols_data[19][1] = {
            {48817}, {53142}, {25050}, {46049}, {55988}, {59666}, {6285},
            {28632}, {60182}, {9603},  {43431}, {5318},  {26286}, {31479},
            {32811}, {10531}, {38399}, {20425}, {60119}};
        element_t res_symbols_data[10][1] = {{4523},  {59642}, {27733}, {29371},
                                             {40673}, {48956}, {41688}, {30236},
                                             {28259}, {43475}};
        symbol_t f_symbols[19] = {
            {.data = f_symbols_data[0]},  {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]},  {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]},  {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]},  {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]},  {.data = f_symbols_data[9]},
            {.data = f_symbols_data[10]}, {.data = f_symbols_data[11]},
            {.data = f_symbols_data[12]}, {.data = f_symbols_data[13]},
            {.data = f_symbols_data[14]}, {.data = f_symbols_data[15]},
            {.data = f_symbols_data[16]}, {.data = f_symbols_data[17]},
            {.data = f_symbols_data[18]}};
        symbol_t res_symbols[10] = {
            {.data = res_symbols_data[0]}, {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]}, {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]}, {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]}, {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]}, {.data = res_symbols_data[9]}};
        symbol_seq_t f = {.symbol_size = 1, .length = 19, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 1, .length = 10, .symbols = res_symbols};
        uint16_t components[10] = {0,     43690, 21845, 26214, 190,
                                   39321, 52428, 32114, 64886, 13107};

        TEST_WRAPPER(fft, f, res, components);
    }

    // Test 2
    {
        element_t f_symbols_data[12][2] = {
            {37025, 7254},  {32385, 7195},  {38506, 24091}, {63967, 15168},
            {13422, 12340}, {37078, 19478}, {54537, 55259}, {17376, 38920},
            {47057, 24941}, {14422, 23433}, {7822, 12546},  {4158, 9928}};
        element_t res_symbols_data[31][2] = {
            {20756, 60501}, {53766, 20092}, {8876, 9450},   {25954, 40544},
            {49434, 25292}, {15518, 16493}, {46988, 49298}, {13330, 11296},
            {20846, 46350}, {40882, 34578}, {38755, 40063}, {60211, 9132},
            {7842, 30507},  {5911, 19172},  {57090, 15246}, {39110, 34725},
            {32677, 20913}, {2879, 38438},  {6557, 40542},  {63907, 64537},
            {7035, 46955},  {2914, 16864},  {4869, 24594},  {58758, 64419},
            {23868, 1610},  {5185, 49851},  {59112, 28739}, {52981, 64109},
            {11936, 815},   {57557, 14976}, {19280, 271}};
        symbol_t f_symbols[12] = {
            {.data = f_symbols_data[0]},  {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]},  {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]},  {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]},  {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]},  {.data = f_symbols_data[9]},
            {.data = f_symbols_data[10]}, {.data = f_symbols_data[11]}};
        symbol_t res_symbols[31] = {
            {.data = res_symbols_data[0]},  {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]},  {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]},  {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]},  {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]},  {.data = res_symbols_data[9]},
            {.data = res_symbols_data[10]}, {.data = res_symbols_data[11]},
            {.data = res_symbols_data[12]}, {.data = res_symbols_data[13]},
            {.data = res_symbols_data[14]}, {.data = res_symbols_data[15]},
            {.data = res_symbols_data[16]}, {.data = res_symbols_data[17]},
            {.data = res_symbols_data[18]}, {.data = res_symbols_data[19]},
            {.data = res_symbols_data[20]}, {.data = res_symbols_data[21]},
            {.data = res_symbols_data[22]}, {.data = res_symbols_data[23]},
            {.data = res_symbols_data[24]}, {.data = res_symbols_data[25]},
            {.data = res_symbols_data[26]}, {.data = res_symbols_data[27]},
            {.data = res_symbols_data[28]}, {.data = res_symbols_data[29]},
            {.data = res_symbols_data[30]}};
        symbol_seq_t f = {.symbol_size = 2, .length = 12, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 2, .length = 31, .symbols = res_symbols};
        uint16_t components[31] = {
            18469, 9544,  48059, 7710,  42002, 38902, 33364, 8341,
            27161, 34695, 56797, 19088, 61680, 30583, 30840, 10817,
            16682, 15420, 36938, 43268, 2386,  47666, 38176, 61166,
            21634, 21001, 50115, 3855,  1193,  4772,  57825};

        TEST_WRAPPER(fft, f, res, components);
    }

    // Test 3
    {
        element_t f_symbols_data[7][3] = {
            {23793, 48866, 42951}, {15142, 45573, 55536}, {41952, 18609, 56207},
            {12763, 39836, 51889}, {47966, 27359, 42972}, {4152, 48934, 10104},
            {48259, 56554, 11962}};
        element_t res_symbols_data[17][3] = {
            {64742, 49490, 2074},  {1608, 24975, 50010},  {24049, 49135, 8348},
            {48502, 31693, 62378}, {15412, 63511, 54347}, {32392, 29434, 50136},
            {28241, 37026, 41799}, {38482, 26366, 23183}, {12824, 38053, 4275},
            {53840, 48703, 37532}, {39268, 37408, 30022}, {49626, 59149, 55180},
            {41161, 50947, 11512}, {5973, 62013, 12656},  {29365, 44783, 15124},
            {57298, 23722, 37793}, {17067, 11700, 3688}};
        symbol_t f_symbols[7] = {
            {.data = f_symbols_data[0]}, {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]}, {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]}, {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]}};
        symbol_t res_symbols[17] = {
            {.data = res_symbols_data[0]},  {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]},  {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]},  {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]},  {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]},  {.data = res_symbols_data[9]},
            {.data = res_symbols_data[10]}, {.data = res_symbols_data[11]},
            {.data = res_symbols_data[12]}, {.data = res_symbols_data[13]},
            {.data = res_symbols_data[14]}, {.data = res_symbols_data[15]},
            {.data = res_symbols_data[16]}};
        symbol_seq_t f = {.symbol_size = 3, .length = 7, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 3, .length = 17, .symbols = res_symbols};
        uint16_t components[17] = {61166, 36545, 21845, 29812, 59624, 48059,
                                   43690, 30583, 18247, 53713, 56797, 14906,
                                   41891, 26127, 32170, 36494, 7453};

        TEST_WRAPPER(fft, f, res, components);
    }

    free_all(fft);

    return 0;
}