#include <stdio.h>

#include <fft.h>

#include <util.h>

#define TEST_WRAPPER(_fft, _f, _positions, _res)                               \
    do {                                                                       \
        if (test((_fft), (_f), (_positions), (_res))) {                        \
            free_all((_fft));                                                  \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static int test(const FFT_t *fft, symbol_seq_t f, const uint16_t *positions,
                symbol_seq_t res) {
    symbol_seq_t _res;
    int ret;

    ret = seq_alloc(res.symbol_size, res.length, &_res);
    if (ret) {
        printf("ERROR: seq_alloc returned %d\n", ret);
        return ret;
    }

    fft_transform(fft, f, positions, _res);

    if (!util_seq_eq(_res, res)) {
        printf("ERROR: fft_transform(...): incorrect res:\n");

        printf("\tcorrect = ");
        util_seq_printf(res);
        printf("\n");

        printf("\tactual  = ");
        util_seq_printf(_res);
        printf("\n");

        ret = 1;
    }

    seq_free(&_res);

    return ret;
}

static int free_all(FFT_t *fft) {
    GF_t *gf = fft->gf;

    fft_free(fft);
    gf_free(gf);
}

int main(void) {
    FFT_t _fft;
    FFT_t *fft = &_fft;

    {
        GF_t _gf;
        GF_t *gf = &_gf;
        int ret;

        ret = gf_alloc(gf);
        if (ret) {
            printf("ERROR: gf_alloc returned %d\n", ret);
            return ret;
        }

        gf_init(gf);

        ret = fft_alloc(fft);
        if (ret) {
            printf("ERROR: fft_alloc returned %d\n", ret);
            gf_free(gf);
            return ret;
        }

        fft_init(fft, gf);
    }

    // Test data obtained by SageMath.
    // Code also was generated by Python and SageMath.

    // Test 1
    {
        element_t f_symbols_data[18][1] = {
            {64380}, {58583}, {51371}, {35114}, {36301}, {53727},
            {55096}, {57863}, {41502}, {53715}, {33804}, {47648},
            {39570}, {41997}, {49971}, {43055}, {1947},  {13482}};
        element_t res_symbols_data[15][1] = {{7252},  {36420}, {12001}, {9482},
                                             {61423}, {47618}, {13544}, {43692},
                                             {42306}, {19291}, {59234}, {5528},
                                             {63032}, {40621}, {50939}};
        symbol_t f_symbols[18] = {
            {.data = f_symbols_data[0]},  {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]},  {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]},  {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]},  {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]},  {.data = f_symbols_data[9]},
            {.data = f_symbols_data[10]}, {.data = f_symbols_data[11]},
            {.data = f_symbols_data[12]}, {.data = f_symbols_data[13]},
            {.data = f_symbols_data[14]}, {.data = f_symbols_data[15]},
            {.data = f_symbols_data[16]}, {.data = f_symbols_data[17]}};
        symbol_t res_symbols[15] = {
            {.data = res_symbols_data[0]},  {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]},  {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]},  {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]},  {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]},  {.data = res_symbols_data[9]},
            {.data = res_symbols_data[10]}, {.data = res_symbols_data[11]},
            {.data = res_symbols_data[12]}, {.data = res_symbols_data[13]},
            {.data = res_symbols_data[14]}};
        symbol_seq_t f = {.symbol_size = 1, .length = 18, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 1, .length = 15, .symbols = res_symbols};
        uint16_t positions[18] = {49223, 41312, 43584, 31160, 51888, 57952,
                                  23906, 10492, 7997,  26938, 59019, 38516,
                                  39098, 43598, 64585, 29211, 12740, 4719};

        TEST_WRAPPER(fft, f, positions, res);
    }

    // Test 2

    {
        element_t f_symbols_data[15][2] = {
            {21166, 59609}, {37601, 32221}, {5359, 64128},  {45274, 58835},
            {1555, 19095},  {37428, 59604}, {37873, 25514}, {56877, 46425},
            {37971, 30481}, {6469, 11827},  {7500, 51432},  {7307, 20467},
            {31112, 51161}, {39231, 31806}, {35783, 57569}};
        element_t res_symbols_data[9][2] = {
            {23072, 31704}, {51, 60435},    {15795, 49266},
            {50312, 17446}, {16259, 38915}, {22497, 43659},
            {17489, 28338}, {6294, 30118},  {7766, 32676}};
        symbol_t f_symbols[15] = {
            {.data = f_symbols_data[0]},  {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]},  {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]},  {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]},  {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]},  {.data = f_symbols_data[9]},
            {.data = f_symbols_data[10]}, {.data = f_symbols_data[11]},
            {.data = f_symbols_data[12]}, {.data = f_symbols_data[13]},
            {.data = f_symbols_data[14]}};
        symbol_t res_symbols[9] = {
            {.data = res_symbols_data[0]}, {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]}, {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]}, {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]}, {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]}};
        symbol_seq_t f = {.symbol_size = 2, .length = 15, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 2, .length = 9, .symbols = res_symbols};
        uint16_t positions[15] = {20188, 33100, 14709, 32299, 21164,
                                  5933,  1056,  2421,  29668, 21124,
                                  28821, 15987, 21278, 4071,  13225};

        TEST_WRAPPER(fft, f, positions, res);
    }

    // Test 3
    {
        element_t f_symbols_data[8][3] = {
            {6985, 38161, 34050},  {24420, 64304, 640},   {45377, 5781, 5813},
            {63411, 30776, 22735}, {37687, 24817, 35692}, {63819, 37912, 23768},
            {39888, 27907, 16983}, {63813, 27111, 3673}};
        element_t res_symbols_data[6][3] = {
            {2614, 61569, 21058}, {50205, 19106, 32252}, {41922, 12561, 7107},
            {37877, 41336, 1929}, {42499, 47538, 47062}, {1398, 34219, 37667}};
        symbol_t f_symbols[8] = {
            {.data = f_symbols_data[0]}, {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]}, {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]}, {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]}, {.data = f_symbols_data[7]}};
        symbol_t res_symbols[6] = {
            {.data = res_symbols_data[0]}, {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]}, {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]}, {.data = res_symbols_data[5]}};
        symbol_seq_t f = {.symbol_size = 3, .length = 8, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 3, .length = 6, .symbols = res_symbols};
        uint16_t positions[8] = {56290, 25198, 60664, 12498,
                                 17443, 57847, 5918,  8521};

        TEST_WRAPPER(fft, f, positions, res);
    }

    free_all(fft);

    return 0;
}