#include <stdio.h>

#include <fft.h>

#include <util.h>

#define TEST_WRAPPER(_fft, _f, _res, _components)                              \
    do {                                                                       \
        if (test((_fft), (_f), (_res), (_components))) {                       \
            free_all((_fft));                                                  \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static int test(const FFT_t *fft, symbol_seq_t f, symbol_seq_t res,
                const uint16_t *components) {
    symbol_seq_t _res;
    int ret;

    ret = seq_alloc(res.symbol_size, res.length, &_res);
    if (ret) {
        printf("ERROR: seq_alloc returned %d\n", ret);
        return ret;
    }

    fft_partial_transform(fft, f, _res, components);

    if (!util_seq_eq(_res, res)) {
        printf("ERROR: fft_partial_transform(...): incorrect res:\n");

        printf("\tcorrect = ");
        util_seq_printf(res);
        printf("\n");

        printf("\tactual  = ");
        util_seq_printf(_res);
        printf("\n");

        ret = 1;
    }

    seq_free(&_res);

    return ret;
}

static int free_all(FFT_t *fft) {
    GF_t *gf = fft->gf;

    fft_free(fft);
    gf_free(gf);
}

int main(void) {
    FFT_t _fft;
    FFT_t *fft = &_fft;

    {
        GF_t _gf;
        GF_t *gf = &_gf;
        int ret;

        ret = gf_alloc(gf);
        if (ret) {
            printf("ERROR: gf_alloc returned %d\n", ret);
            return ret;
        }

        gf_init(gf);

        ret = fft_alloc(fft);
        if (ret) {
            printf("ERROR: fft_alloc returned %d\n", ret);
            gf_free(gf);
            return ret;
        }

        fft_init(fft, gf);
    }

    // Test data obtained by SageMath.
    // Code also was generated by Python and SageMath.

    // Test 1
    {
        element_t f_symbols_data[22][1] = {
            {11785}, {22472}, {48159}, {22958}, {55989}, {63830},
            {24045}, {63587}, {42653}, {15544}, {51692}, {11620},
            {52835}, {2742},  {22150}, {48988}, {23802}, {3281},
            {24646}, {41651}, {63369}, {43085}};
        element_t res_symbols_data[25][1] = {
            {10918}, {33532}, {50715}, {44207}, {9620},  {3680},  {1385},
            {37418}, {9861},  {49343}, {25832}, {37367}, {64803}, {353},
            {9557},  {56437}, {11969}, {30209}, {19918}, {52954}, {33548},
            {25147}, {25312}, {3558},  {51410}};
        symbol_t f_symbols[22] = {
            {.data = f_symbols_data[0]},  {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]},  {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]},  {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]},  {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]},  {.data = f_symbols_data[9]},
            {.data = f_symbols_data[10]}, {.data = f_symbols_data[11]},
            {.data = f_symbols_data[12]}, {.data = f_symbols_data[13]},
            {.data = f_symbols_data[14]}, {.data = f_symbols_data[15]},
            {.data = f_symbols_data[16]}, {.data = f_symbols_data[17]},
            {.data = f_symbols_data[18]}, {.data = f_symbols_data[19]},
            {.data = f_symbols_data[20]}, {.data = f_symbols_data[21]}};
        symbol_t res_symbols[25] = {
            {.data = res_symbols_data[0]},  {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]},  {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]},  {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]},  {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]},  {.data = res_symbols_data[9]},
            {.data = res_symbols_data[10]}, {.data = res_symbols_data[11]},
            {.data = res_symbols_data[12]}, {.data = res_symbols_data[13]},
            {.data = res_symbols_data[14]}, {.data = res_symbols_data[15]},
            {.data = res_symbols_data[16]}, {.data = res_symbols_data[17]},
            {.data = res_symbols_data[18]}, {.data = res_symbols_data[19]},
            {.data = res_symbols_data[20]}, {.data = res_symbols_data[21]},
            {.data = res_symbols_data[22]}, {.data = res_symbols_data[23]},
            {.data = res_symbols_data[24]}};
        symbol_seq_t f = {.symbol_size = 1, .length = 22, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 1, .length = 25, .symbols = res_symbols};
        uint16_t components[25] = {
            22970, 48059, 61166, 14155, 56620, 30583, 53991, 42395, 43690,
            11485, 59750, 52690, 56797, 19255, 60197, 47705, 29875, 26345,
            28310, 53965, 39845, 38510, 45940, 21845, 12091};

        TEST_WRAPPER(fft, f, res, components);
    }

    // Test 2
    {
        element_t f_symbols_data[15][2] = {
            {47556, 20926}, {62258, 34390}, {2123, 41849},  {36975, 2892},
            {23714, 46737}, {3505, 30801},  {19746, 31611}, {31012, 12338},
            {1185, 37563},  {46404, 64986}, {32212, 1478},  {60550, 30543},
            {10796, 37902}, {21970, 16183}, {9418, 3231}};
        element_t res_symbols_data[22][2] = {
            {17129, 52526}, {50815, 42156}, {45251, 17564}, {28427, 58129},
            {17572, 14598}, {54366, 53402}, {54275, 44524}, {52292, 16410},
            {30028, 50537}, {56610, 17447}, {63177, 23974}, {29696, 44744},
            {29575, 46596}, {51262, 62452}, {65063, 22182}, {29572, 20280},
            {21873, 15068}, {43385, 36247}, {26116, 31704}, {40762, 17680},
            {11026, 22561}, {48055, 21157}};
        symbol_t f_symbols[15] = {
            {.data = f_symbols_data[0]},  {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]},  {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]},  {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]},  {.data = f_symbols_data[7]},
            {.data = f_symbols_data[8]},  {.data = f_symbols_data[9]},
            {.data = f_symbols_data[10]}, {.data = f_symbols_data[11]},
            {.data = f_symbols_data[12]}, {.data = f_symbols_data[13]},
            {.data = f_symbols_data[14]}};
        symbol_t res_symbols[22] = {
            {.data = res_symbols_data[0]},  {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]},  {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]},  {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]},  {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]},  {.data = res_symbols_data[9]},
            {.data = res_symbols_data[10]}, {.data = res_symbols_data[11]},
            {.data = res_symbols_data[12]}, {.data = res_symbols_data[13]},
            {.data = res_symbols_data[14]}, {.data = res_symbols_data[15]},
            {.data = res_symbols_data[16]}, {.data = res_symbols_data[17]},
            {.data = res_symbols_data[18]}, {.data = res_symbols_data[19]},
            {.data = res_symbols_data[20]}, {.data = res_symbols_data[21]}};
        symbol_seq_t f = {.symbol_size = 2, .length = 15, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 2, .length = 22, .symbols = res_symbols};
        uint16_t components[22] = {43690, 17375, 46477, 46121, 42704, 34102,
                                   21352, 0,     21845, 2669,  41293, 39746,
                                   19873, 27914, 26707, 10676, 3337,  5338,
                                   55828, 53414, 17051, 13957};

        TEST_WRAPPER(fft, f, res, components);
    }

    // Test 3
    {
        element_t f_symbols_data[8][3] = {
            {32696, 28179, 29962}, {54137, 17790, 3577},  {14406, 26489, 53808},
            {35945, 36335, 63731}, {47328, 47545, 21518}, {29976, 34568, 9594},
            {25470, 22737, 46088}, {28366, 52128, 54750}};
        element_t res_symbols_data[25][3] = {
            {41067, 26158, 59738}, {21838, 54843, 36755}, {2344, 64865, 26654},
            {50751, 49904, 46944}, {58208, 8323, 25071},  {14700, 29662, 3719},
            {16430, 29678, 56824}, {60703, 48722, 8446},  {55888, 45509, 6634},
            {54289, 23266, 42223}, {25765, 26114, 49141}, {54428, 10531, 37535},
            {32851, 45704, 61288}, {36611, 41995, 47757}, {33929, 51635, 59864},
            {59490, 45368, 37433}, {40427, 24859, 59341}, {27402, 49408, 2006},
            {54340, 34486, 38674}, {54027, 25800, 37364}, {20299, 44669, 22428},
            {15972, 2233, 44687},  {58993, 10333, 27097}, {46755, 22291, 6169},
            {65423, 59530, 7321}};
        symbol_t f_symbols[8] = {
            {.data = f_symbols_data[0]}, {.data = f_symbols_data[1]},
            {.data = f_symbols_data[2]}, {.data = f_symbols_data[3]},
            {.data = f_symbols_data[4]}, {.data = f_symbols_data[5]},
            {.data = f_symbols_data[6]}, {.data = f_symbols_data[7]}};
        symbol_t res_symbols[25] = {
            {.data = res_symbols_data[0]},  {.data = res_symbols_data[1]},
            {.data = res_symbols_data[2]},  {.data = res_symbols_data[3]},
            {.data = res_symbols_data[4]},  {.data = res_symbols_data[5]},
            {.data = res_symbols_data[6]},  {.data = res_symbols_data[7]},
            {.data = res_symbols_data[8]},  {.data = res_symbols_data[9]},
            {.data = res_symbols_data[10]}, {.data = res_symbols_data[11]},
            {.data = res_symbols_data[12]}, {.data = res_symbols_data[13]},
            {.data = res_symbols_data[14]}, {.data = res_symbols_data[15]},
            {.data = res_symbols_data[16]}, {.data = res_symbols_data[17]},
            {.data = res_symbols_data[18]}, {.data = res_symbols_data[19]},
            {.data = res_symbols_data[20]}, {.data = res_symbols_data[21]},
            {.data = res_symbols_data[22]}, {.data = res_symbols_data[23]},
            {.data = res_symbols_data[24]}};
        symbol_seq_t f = {.symbol_size = 3, .length = 8, .symbols = f_symbols};
        symbol_seq_t res = {
            .symbol_size = 3, .length = 25, .symbols = res_symbols};
        uint16_t components[25] = {
            21845, 47796, 11949, 39321, 20839, 42453, 13107, 46266, 19371,
            38742, 43851, 30057, 26214, 23133, 22167, 43690, 26997, 46280,
            52428, 54693, 23898, 60114, 44334, 38650, 53994};

        TEST_WRAPPER(fft, f, res, components);
    }

    // TODO: implement

    free_all(fft);

    return 0;
}