#include <stdio.h>
#include <string.h>

#include <reed_solomon.h>

#include <util.h>

#define TEST_WRAPPER(_rs, _k, _r, _src_symbols, _erased_indices, _t)           \
    do {                                                                       \
        if (test((_rs), (_k), (_r), (_src_symbols), (_erased_indices),         \
                 (_t))) {                                                      \
            free_all((_rs));                                                   \
            return 1;                                                          \
        }                                                                      \
    } while (0)

static int test(const RS_t *rs, uint16_t k, uint16_t r,
                symbol_seq_t src_symbols, const uint16_t *erased_indices,
                uint16_t t) {
    symbol_seq_t rcv_symbols;
    int ret;

    ret = seq_alloc(src_symbols.symbol_size, src_symbols.length, &rcv_symbols);
    if (ret) {
        printf("ERROR: seq_alloc returned %d\n", ret);
        return ret;
    }

    for (uint16_t i = 0; i < src_symbols.length; ++i) {
        memcpy((void *)rcv_symbols.symbols[i].data,
               (void *)src_symbols.symbols[i].data,
               src_symbols.symbol_size * sizeof(element_t));
    }

    for (uint16_t i = 0; i < t; ++i) {
        memset((void *)rcv_symbols.symbols[erased_indices[i]].data, 0,
               rcv_symbols.symbol_size * sizeof(element_t));
    }

    rs_restore_symbols(rs, k, r, rcv_symbols, erased_indices, t);

    if (!util_seq_eq(rcv_symbols, src_symbols)) {
        printf("ERROR: rs_restore_symbols(...): incorrect rcv_symbols:\n");

        printf("\tcorrect = ");
        util_seq_printf(src_symbols);
        printf("\n");

        printf("\tactual  = ");
        util_seq_printf(rcv_symbols);
        printf("\n");

        ret = 1;
    }

    seq_free(&rcv_symbols);

    return ret;
}

static void free_all(RS_t *rs) {
    GF_t *gf = rs->gf;
    CC_t *cc = rs->cc;
    FFT_t *fft = rs->fft;

    rs_free(rs);
    fft_free(fft);
    cc_free(cc);
    gf_free(gf);
}

int main(void) {
    GF_t _gf;
    CC_t _cc;
    FFT_t _fft;
    RS_t _rs;
    RS_t *rs = &_rs;

    {
        GF_t *gf = &_gf;
        CC_t *cc = &_cc;
        FFT_t *fft = &_fft;

        int ret = 0;

        ret = gf_alloc(gf);
        if (ret) {
            printf("ERROR: gf_alloc returned %d\n", ret);
            return ret;
        }

        gf_init(gf);

        ret = cc_alloc(cc);
        if (ret) {
            printf("ERROR: cc_alloc returned %d\n", ret);
            gf_free(gf);
            return ret;
        }

        cc_init(cc);

        ret = fft_alloc(fft);
        if (ret) {
            printf("ERROR: fft_alloc returned %d\n", ret);
            cc_free(cc);
            gf_free(gf);
            return ret;
        }

        fft_init(fft, gf);

        ret = rs_alloc(rs);
        if (ret) {
            printf("ERROR: rs_alloc returned %d\n", ret);
            fft_free(fft);
            cc_free(cc);
            gf_free(gf);
            return ret;
        }

        rs_init(rs, gf, cc, fft);
    }

    // Test data obtained by SageMath.
    // Code also was generated by Python and SageMath.

    // Test 1
    {
        uint16_t k = 24;
        uint16_t r = 15;
        uint16_t t = 12;
        element_t rcv_symbols_data[39][1] = {
            {45100}, {44816}, {14317}, {14605}, {39619}, {14144}, {33136},
            {47610}, {11155}, {6240},  {9065},  {27926}, {31952}, {44615},
            {44897}, {58344}, {3297},  {21777}, {36711}, {5053},  {44272},
            {24319}, {21107}, {17830}, {48152}, {46421}, {16974}, {26755},
            {40689}, {2995},  {20301}, {34240}, {58232}, {12357}, {18371},
            {41310}, {11768}, {54399}, {63455}};
        symbol_t rcv_symbols_array[39] = {
            {.data = rcv_symbols_data[0]},  {.data = rcv_symbols_data[1]},
            {.data = rcv_symbols_data[2]},  {.data = rcv_symbols_data[3]},
            {.data = rcv_symbols_data[4]},  {.data = rcv_symbols_data[5]},
            {.data = rcv_symbols_data[6]},  {.data = rcv_symbols_data[7]},
            {.data = rcv_symbols_data[8]},  {.data = rcv_symbols_data[9]},
            {.data = rcv_symbols_data[10]}, {.data = rcv_symbols_data[11]},
            {.data = rcv_symbols_data[12]}, {.data = rcv_symbols_data[13]},
            {.data = rcv_symbols_data[14]}, {.data = rcv_symbols_data[15]},
            {.data = rcv_symbols_data[16]}, {.data = rcv_symbols_data[17]},
            {.data = rcv_symbols_data[18]}, {.data = rcv_symbols_data[19]},
            {.data = rcv_symbols_data[20]}, {.data = rcv_symbols_data[21]},
            {.data = rcv_symbols_data[22]}, {.data = rcv_symbols_data[23]},
            {.data = rcv_symbols_data[24]}, {.data = rcv_symbols_data[25]},
            {.data = rcv_symbols_data[26]}, {.data = rcv_symbols_data[27]},
            {.data = rcv_symbols_data[28]}, {.data = rcv_symbols_data[29]},
            {.data = rcv_symbols_data[30]}, {.data = rcv_symbols_data[31]},
            {.data = rcv_symbols_data[32]}, {.data = rcv_symbols_data[33]},
            {.data = rcv_symbols_data[34]}, {.data = rcv_symbols_data[35]},
            {.data = rcv_symbols_data[36]}, {.data = rcv_symbols_data[37]},
            {.data = rcv_symbols_data[38]}};
        symbol_seq_t rcv_symbols = {
            .symbol_size = 1, .length = 39, .symbols = rcv_symbols_array};
        uint16_t erased_indices[12] = {7,  38, 16, 33, 15, 25,
                                       27, 2,  5,  30, 11, 24};

        TEST_WRAPPER(rs, k, r, rcv_symbols, erased_indices, t);
    }

    // Test 2
    {
        uint16_t k = 11;
        uint16_t r = 9;
        uint16_t t = 9;
        element_t rcv_symbols_data[20][2] = {
            {21077, 59249}, {51477, 43149}, {50557, 27336}, {40204, 52243},
            {53043, 2522},  {62456, 19727}, {32103, 6835},  {32456, 22811},
            {23396, 5399},  {3297, 10260},  {49033, 62857}, {17411, 21680},
            {58842, 52508}, {34182, 23221}, {40140, 17215}, {50916, 50726},
            {21565, 5511},  {48243, 12175}, {49927, 15781}, {16743, 26493}};
        symbol_t rcv_symbols_array[20] = {
            {.data = rcv_symbols_data[0]},  {.data = rcv_symbols_data[1]},
            {.data = rcv_symbols_data[2]},  {.data = rcv_symbols_data[3]},
            {.data = rcv_symbols_data[4]},  {.data = rcv_symbols_data[5]},
            {.data = rcv_symbols_data[6]},  {.data = rcv_symbols_data[7]},
            {.data = rcv_symbols_data[8]},  {.data = rcv_symbols_data[9]},
            {.data = rcv_symbols_data[10]}, {.data = rcv_symbols_data[11]},
            {.data = rcv_symbols_data[12]}, {.data = rcv_symbols_data[13]},
            {.data = rcv_symbols_data[14]}, {.data = rcv_symbols_data[15]},
            {.data = rcv_symbols_data[16]}, {.data = rcv_symbols_data[17]},
            {.data = rcv_symbols_data[18]}, {.data = rcv_symbols_data[19]}};
        symbol_seq_t rcv_symbols = {
            .symbol_size = 2, .length = 20, .symbols = rcv_symbols_array};
        uint16_t erased_indices[9] = {13, 11, 17, 5, 6, 3, 0, 18, 16};

        TEST_WRAPPER(rs, k, r, rcv_symbols, erased_indices, t);
    }

    // Test 3
    {
        uint16_t k = 9;
        uint16_t r = 6;
        uint16_t t = 6;
        element_t rcv_symbols_data[15][3] = {
            {30234, 54688, 40968}, {62001, 57116, 53248}, {59608, 40439, 47910},
            {40449, 44643, 1356},  {41281, 61935, 24043}, {20928, 64334, 28787},
            {551, 33036, 16640},   {54685, 57197, 62733}, {27135, 7861, 42303},
            {26749, 9013, 13320},  {15209, 7220, 20689},  {62126, 34159, 34348},
            {22415, 10559, 35455}, {23533, 63689, 15527}, {4590, 6341, 42725}};
        symbol_t rcv_symbols_array[15] = {
            {.data = rcv_symbols_data[0]},  {.data = rcv_symbols_data[1]},
            {.data = rcv_symbols_data[2]},  {.data = rcv_symbols_data[3]},
            {.data = rcv_symbols_data[4]},  {.data = rcv_symbols_data[5]},
            {.data = rcv_symbols_data[6]},  {.data = rcv_symbols_data[7]},
            {.data = rcv_symbols_data[8]},  {.data = rcv_symbols_data[9]},
            {.data = rcv_symbols_data[10]}, {.data = rcv_symbols_data[11]},
            {.data = rcv_symbols_data[12]}, {.data = rcv_symbols_data[13]},
            {.data = rcv_symbols_data[14]}};
        symbol_seq_t rcv_symbols = {
            .symbol_size = 3, .length = 15, .symbols = rcv_symbols_array};
        uint16_t erased_indices[6] = {8, 11, 13, 2, 0, 1};

        TEST_WRAPPER(rs, k, r, rcv_symbols, erased_indices, t);
    }

    free_all(rs);

    return 0;
}